name:                Jambda
version:             0.1.0.0
github:              "aaronallen8455/Jambda"
license:             BSD3
author:              "Aaron Allen"
maintainer:          "aaronallen8455@gmail.com"
copyright:           "2019 Aaron Allen"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Synth#readme>

dependencies:
- base >= 4.7 && < 5
- brick
- comonad
- containers
- data-clist
- free
- lens
- megaparsec
- mtl
- sdl2
- streams
- text-zipper
- transformers
- vector
- vty

executables:
  Jambda-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -Wall
    - -Werror
    - -with-rtsopts=-N

tests:
  Synth-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
